version: '3'
services:
  # HAProxy for multiple apps, etc
  # big TODO
  proxy:
    image: haproxy:latest
    # command: /sbin/syslogd -O /proc/1/fd/1 -R localhost && haproxy -f /usr/local/etc/haproxy/haproxy.cfg # Add logging to stdout by default
    volumes:
      - ./haproxy:/usr/local/etc/haproxy #haproxy.cfg
      - /dev/log:/dev/log
    ports:
      - "80:80"
    networks:
      - frontend
  # proxy:
  #   image: proxyd:latest
  #   build: ./proxyd
  #   ports:
  #     - "80:80"
  #   networks:
  #     - frontend

  portainer:
    image: portainer/portainer
    ports:
      - "9000"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - frontend

  blog:
    image: ghost:latest
    ports:
      - "2368"
    volumes:
      - ghost-data:/var/lib/ghost/
    networks:
      - frontend
  web:
    image: web:latest
    build: ./web
    volumes:
      - html:/usr/share/nginx/html
    ports:
      - "80"
    networks:
      - frontend
networks:
  frontend:
  backend:
volumes:
  ghost-data:
  html:

