version: '3'
services:
  # HAProxy for multiple apps, etc
  # big TODO
  proxy:
    image: proxy:latest
    # init: true # Properly forward stop signals to the child proccesses (syslogd and haproxy)
    build: ./proxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy #haproxy.cfg
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blog
      - web
      - portainer
      - company
    networks:
      - frontend
      - infra
  blog:
    image: ghost:alpine
    ports:
      - "2368"
    volumes:
      - ghost-data:/var/lib/ghost/
    networks:
      - frontend
  web:
    image: web:latest
    build: ./web
    volumes:
      - html:/usr/share/nginx/html
    ports:
      - "80"
    networks:
      - frontend
  company:
    image: nginx
    build: ./web
    volumes:
      - ./company:/usr/share/nginx/html
    ports:
      - "80"
    networks:
      - frontend
  certbot:
    # Placeholder for HAProxy
    image: nginx
    ports:
      - "80"
    networks:
      - infra
    # image: cert-manager:latest
    # build: ./cert-manager

  portainer:
    image: portainer/portainer
    ports:
      - "9000"
    deploy:
      placement:
        constraints:
          - "node.role == manager"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - infra
networks:
  frontend:
  infra:
volumes:
  ghost-data:
  html:
